// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int number = Integer.parseInt(args[0]);
		int smaller = 0;
		int bigger = 0;
		double ratio = 0;
		for (int i = 0; i < number; i++){
			double random = Math.random();
		if (random <= 0.5)
		{
			smaller++;
		}
		else
		{
			bigger++;
		}
		}
		System.out.println("> 0.5: " + bigger + " times");
		System.out.println("<= 0.5: " + smaller + " times");
		if ( bigger != 0 && smaller !=0) {
		if (bigger >= smaller) {
			ratio = (double) smaller / bigger;
			System.out.println("ratio: " +  ratio);
		} else {
			ratio = (double) bigger / smaller; 
			System.out.println("ratio: " +  ratio);
			}
		}	
	}
}