// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int number = Integer.parseInt(args[0]);
		int smaller = 0;
		int bigger = 0;
		for (int i = 0; i < number; i++){
			double random = Math.random();
			//int y = (int) ((number + 1) ); // the number from the lottery
		if (random <= 0.5)
		{
			smaller++;
		}
		else
		{
			bigger++;
		}
		}
		System.out.println("> 0.5: " + bigger + " times");
		System.out.println("<= 0.5: " + smaller + " times");
		if (smaller > 0){
			double ratio = (double) smaller / bigger;
			System.out.println("ratio: " +  ratio);
		} 	
	}
}